# Generated by Django 4.0.5 on 2022-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("studio", models.CharField(max_length=255)),
                ("producer", models.CharField(max_length=255)),
                ("winner", models.BooleanField()),
            ],
        ),
    ]
